# Generated by Django 4.1.4 on 2022-12-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="название экзамена"),
                ),
                ("date", models.DateField(verbose_name="дата экзамена")),
                ("creator", models.CharField(max_length=300, verbose_name="создатель")),
                ("num_question", models.IntegerField(verbose_name="кол-во вопросов")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=300, verbose_name="автор экзамена"),
                ),
                ("text", models.TextField(verbose_name="текст вопроса")),
                ("number", models.IntegerField(verbose_name="номер вопроса")),
                (
                    "answer",
                    models.FileField(
                        upload_to="data/None", verbose_name="ответ на вопрос"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
            ],
        ),
    ]
