# Generated by Django 4.1.4 on 2022-12-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"verbose_name": "Экзамен", "verbose_name_plural": "Экзамены"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AddField(
            model_name="question",
            name="finished",
            field=models.BooleanField(default=False, verbose_name="статус"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.FileField(upload_to="", verbose_name="ответ на вопрос"),
        ),
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.CharField(max_length=300, verbose_name="автор вопроса"),
        ),
    ]
