# Generated by Django 4.1.4 on 2022-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_exam_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.FileField(
                upload_to="data/None", verbose_name="ответ на вопрос"
            ),
        ),
    ]
