# Generated by Django 4.1.4 on 2022-12-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.FileField(upload_to="data/", verbose_name="ответ на вопрос"),
        ),
    ]
