# Generated by Django 4.1.4 on 2022-12-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_alter_exam_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="grade",
            field=models.IntegerField(default=0, verbose_name="курс обучения"),
            preserve_default=False,
        ),
    ]
