# Generated by Django 4.1.4 on 2022-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_exam_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="num_finished",
            field=models.IntegerField(
                default=0, verbose_name="кол-во законченных вопросов"
            ),
            preserve_default=False,
        ),
    ]
